/**
 * G-code Parser
 * Parses G-code files to extract print statistics from embedded comments
 * Supports both Cura and PrusaSlicer formats
 */

export interface GcodeStats {
    printTimeMinutes: number
    filamentMm: number
    filamentGrams: number
    layerCount: number
    flavor: string | null
    slicer: string | null
}

// Filament diameter and material densities for calculating weight
const FILAMENT_DIAMETER = 1.75 // mm
const MATERIAL_DENSITY: Record<string, number> = {
    pla: 1.24,
    abs: 1.04,
    petg: 1.27,
    tpu: 1.21,
}

/**
 * Parse G-code content to extract print statistics
 * This only reads the first ~500 lines and last ~200 lines where metadata is typically stored
 */
export async function parseGcodeFile(file: File, material: string = 'pla'): Promise<GcodeStats> {
    const text = await file.text()
    return parseGcodeStats(text, material)
}

export function parseGcodeStats(gcode: string, material: string = 'pla'): GcodeStats {
    let printTimeMinutes = 0
    let filamentMm = 0
    let filamentGrams = 0
    let layerCount = 0
    let flavor: string | null = null
    let slicer: string | null = null

    const lines = gcode.split('\n')

    // Parse first 500 lines (header) and last 200 lines (config section)
    const linesToCheck = [
        ...lines.slice(0, 500),
        ...lines.slice(-200)
    ]

    for (const line of linesToCheck) {
        const trimmedLine = line.trim()

        // Skip non-comment lines for metadata
        if (!trimmedLine.startsWith(';')) continue

        // === SLICER DETECTION ===
        // Cura format
        if (trimmedLine.includes('Generated with Cura')) {
            slicer = 'Cura'
            const match = trimmedLine.match(/Cura[_\s]?(?:SteamEngine\s+)?(\d+\.\d+(?:\.\d+)?)/i)
            if (match) slicer = `Cura ${match[1]}`
        }
        // PrusaSlicer format
        if (trimmedLine.includes('generated by PrusaSlicer')) {
            slicer = 'PrusaSlicer'
            const match = trimmedLine.match(/PrusaSlicer\s+(\d+\.\d+(?:\.\d+)?)/i)
            if (match) slicer = `PrusaSlicer ${match[1]}`
        }
        // SuperSlicer
        if (trimmedLine.includes('generated by SuperSlicer')) {
            slicer = 'SuperSlicer'
        }

        // === G-CODE FLAVOR ===
        // Cura format: ;FLAVOR:Marlin
        if (trimmedLine.startsWith(';FLAVOR:')) {
            flavor = trimmedLine.replace(';FLAVOR:', '').trim()
        }
        // PrusaSlicer format: ; gcode_flavor = marlin
        if (trimmedLine.includes('gcode_flavor')) {
            const match = trimmedLine.match(/gcode_flavor\s*=\s*(\w+)/)
            if (match) flavor = match[1]
        }

        // === PRINT TIME ===
        // Cura format: ;TIME:1234 (in seconds)
        if (trimmedLine.startsWith(';TIME:')) {
            const seconds = parseInt(trimmedLine.replace(';TIME:', '').trim())
            if (!isNaN(seconds)) {
                printTimeMinutes = Math.ceil(seconds / 60)
            }
        }
        // PrusaSlicer format: ; estimated printing time (normal mode) = 1h 23m 45s
        if (trimmedLine.includes('estimated printing time')) {
            const match = trimmedLine.match(/(\d+)h\s*(\d+)m\s*(\d+)s/)
            if (match) {
                const hours = parseInt(match[1]) || 0
                const minutes = parseInt(match[2]) || 0
                const seconds = parseInt(match[3]) || 0
                printTimeMinutes = hours * 60 + minutes + Math.ceil(seconds / 60)
            } else {
                // Try format: 1d 2h 3m 4s
                const dayMatch = trimmedLine.match(/(\d+)d/)
                const hourMatch = trimmedLine.match(/(\d+)h/)
                const minMatch = trimmedLine.match(/(\d+)m/)
                const days = dayMatch ? parseInt(dayMatch[1]) : 0
                const hours = hourMatch ? parseInt(hourMatch[1]) : 0
                const minutes = minMatch ? parseInt(minMatch[1]) : 0
                printTimeMinutes = days * 24 * 60 + hours * 60 + minutes
            }
        }

        // === FILAMENT USAGE ===
        // Cura format: ;Filament used: 0.73581m
        if (trimmedLine.includes(';Filament used:')) {
            const match = trimmedLine.match(/;Filament used:\s*([\d.]+)m/)
            if (match) {
                filamentMm = parseFloat(match[1]) * 1000 // Convert m to mm
            }
        }
        // PrusaSlicer format: ; filament used [mm] = 1234.56
        if (trimmedLine.includes('filament used [mm]')) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match) {
                filamentMm = parseFloat(match[1])
            }
        }
        // PrusaSlicer format: ; filament used [g] = 45.67
        if (trimmedLine.includes('filament used [g]')) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match) {
                filamentGrams = parseFloat(match[1])
            }
        }

        // === LAYER COUNT ===
        // Cura format: ;LAYER_COUNT:123
        if (trimmedLine.startsWith(';LAYER_COUNT:')) {
            layerCount = parseInt(trimmedLine.replace(';LAYER_COUNT:', '').trim()) || 0
        }
        // PrusaSlicer format: ; total layers count = 123
        if (trimmedLine.includes('total layers count')) {
            const match = trimmedLine.match(/=\s*(\d+)/)
            if (match) {
                layerCount = parseInt(match[1])
            }
        }
    }

    // If filament grams not found, calculate from mm
    if (filamentGrams === 0 && filamentMm > 0) {
        const radius = FILAMENT_DIAMETER / 2
        const volumeMm3 = Math.PI * radius * radius * filamentMm
        const volumeCm3 = volumeMm3 / 1000
        const density = MATERIAL_DENSITY[material] || 1.24
        filamentGrams = volumeCm3 * density
    }

    return {
        printTimeMinutes,
        filamentMm,
        filamentGrams: Math.round(filamentGrams * 100) / 100,
        layerCount,
        flavor,
        slicer,
    }
}

/**
 * Check if a file is a G-code file by extension
 */
export function isGcodeFile(file: File): boolean {
    return file.name.toLowerCase().endsWith('.gcode')
}

/**
 * Format print time in human-readable format
 */
export function formatPrintTime(minutes: number): string {
    if (minutes < 60) {
        return `${minutes}m`
    }
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    if (hours < 24) {
        return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`
    }
    const days = Math.floor(hours / 24)
    const remainingHours = hours % 24
    return `${days}d ${remainingHours}h`
}
