/**
 * G-code Parser
 * Parses G-code files to extract print statistics from embedded comments
 * Supports both Cura and PrusaSlicer formats
 */

export interface GcodeStats {
    printTimeMinutes: number
    filamentMm: number
    filamentGrams: number
    layerCount: number
    flavor: string | null
    slicer: string | null
    material: string | null  // Detected material type (pla, abs, petg, etc.)
}

export interface GcodeCompatibility {
    bedSizeX: number | null
    bedSizeY: number | null
    bedSizeZ: number | null
    nozzleDiameter: number | null
    layerHeight: number | null
    bedTemp: number | null
    nozzleTemp: number | null
    warnings: string[]
}

export interface GcodeParseResult extends GcodeStats {
    compatibility: GcodeCompatibility
}

// Filament diameter and material densities for calculating weight
const FILAMENT_DIAMETER = 1.75 // mm
const MATERIAL_DENSITY: Record<string, number> = {
    pla: 1.24,
    abs: 1.04,
    petg: 1.27,
    tpu: 1.21,
}

/**
 * Parse G-code content to extract print statistics
 * This only reads the first ~500 lines and last ~200 lines where metadata is typically stored
 */
export async function parseGcodeFile(file: File, material: string = 'pla'): Promise<GcodeParseResult> {
    const text = await file.text()
    return parseGcodeStats(text, material)
}

export function parseGcodeStats(gcode: string, material: string = 'pla'): GcodeParseResult {
    let printTimeMinutes = 0
    let filamentMm = 0
    let filamentGrams = 0
    let layerCount = 0
    let flavor: string | null = null
    let slicer: string | null = null
    let detectedMaterial: string | null = null

    // Compatibility info
    let bedSizeX: number | null = null
    let bedSizeY: number | null = null
    let bedSizeZ: number | null = null
    let nozzleDiameter: number | null = null
    let layerHeight: number | null = null
    let bedTemp: number | null = null
    let nozzleTemp: number | null = null
    const warnings: string[] = []

    const lines = gcode.split('\n')

    // Parse first 500 lines (header) and last 500 lines (config section for PrusaSlicer)
    const linesToCheck = [
        ...lines.slice(0, 500),
        ...lines.slice(-500)
    ]

    for (const line of linesToCheck) {
        const trimmedLine = line.trim()

        // === SLICER DETECTION ===
        // Cura format
        if (trimmedLine.includes('Generated with Cura')) {
            slicer = 'Cura'
            const match = trimmedLine.match(/Cura[_\s]?(?:SteamEngine\s+)?(\d+\.\d+(?:\.\d+)?)/i)
            if (match) slicer = `Cura ${match[1]}`
        }
        // PrusaSlicer format
        if (trimmedLine.includes('generated by PrusaSlicer')) {
            slicer = 'PrusaSlicer'
            const match = trimmedLine.match(/PrusaSlicer\s+(\d+\.\d+(?:\.\d+)?)/i)
            if (match) slicer = `PrusaSlicer ${match[1]}`
        }
        // SuperSlicer
        if (trimmedLine.includes('generated by SuperSlicer')) {
            slicer = 'SuperSlicer'
        }

        // === G-CODE FLAVOR ===
        // Cura format: ;FLAVOR:Marlin
        if (trimmedLine.startsWith(';FLAVOR:')) {
            flavor = trimmedLine.replace(';FLAVOR:', '').trim()
        }
        // PrusaSlicer format: ; gcode_flavor = marlin
        if (trimmedLine.includes('gcode_flavor')) {
            const match = trimmedLine.match(/gcode_flavor\s*=\s*(\w+)/)
            if (match) flavor = match[1]
        }

        // === MATERIAL TYPE ===
        // Cura format: ;MATERIAL:PLA or ;Filament type = PLA
        if (trimmedLine.includes(';MATERIAL:')) {
            const mat = trimmedLine.replace(';MATERIAL:', '').trim().toLowerCase()
            if (['pla', 'abs', 'petg', 'tpu'].includes(mat)) detectedMaterial = mat
        }
        // PrusaSlicer format: ; filament_type = PLA
        if (trimmedLine.includes('filament_type')) {
            const match = trimmedLine.match(/filament_type\s*=\s*(\w+)/i)
            if (match) {
                const mat = match[1].toLowerCase()
                if (['pla', 'abs', 'petg', 'tpu'].includes(mat)) detectedMaterial = mat
            }
        }
        // Generic: ; material = PLA or ; filament = PLA
        if ((trimmedLine.includes('material =') || trimmedLine.includes('filament =')) && !detectedMaterial) {
            const match = trimmedLine.match(/(?:material|filament)\s*=\s*(\w+)/i)
            if (match) {
                const mat = match[1].toLowerCase()
                if (['pla', 'abs', 'petg', 'tpu'].includes(mat)) detectedMaterial = mat
            }
        }
        // Cura: ;Filament type: PLA
        if (trimmedLine.includes('Filament type:') && !detectedMaterial) {
            const match = trimmedLine.match(/Filament type:\s*(\w+)/i)
            if (match) {
                const mat = match[1].toLowerCase()
                if (['pla', 'abs', 'petg', 'tpu'].includes(mat)) detectedMaterial = mat
            }
        }

        // === BED SIZE ===
        // Cura format: ;MAXX:220, ;MAXY:220
        if (trimmedLine.startsWith(';MAXX:')) {
            bedSizeX = parseFloat(trimmedLine.replace(';MAXX:', '').trim())
        }
        if (trimmedLine.startsWith(';MAXY:')) {
            bedSizeY = parseFloat(trimmedLine.replace(';MAXY:', '').trim())
        }
        if (trimmedLine.startsWith(';MAXZ:')) {
            bedSizeZ = parseFloat(trimmedLine.replace(';MAXZ:', '').trim())
        }
        // PrusaSlicer format: ; bed_shape = 0x0,250x0,250x210,0x210
        if (trimmedLine.includes('bed_shape')) {
            const match = trimmedLine.match(/(\d+)x(\d+),(\d+)x(\d+),(\d+)x(\d+),(\d+)x(\d+)/)
            if (match) {
                bedSizeX = Math.max(parseFloat(match[3]), parseFloat(match[5]))
                bedSizeY = Math.max(parseFloat(match[4]), parseFloat(match[6]))
            }
        }

        // === NOZZLE DIAMETER ===
        // PrusaSlicer: ; nozzle_diameter = 0.4
        if (trimmedLine.includes('nozzle_diameter')) {
            const match = trimmedLine.match(/nozzle_diameter\s*=\s*([\d.]+)/)
            if (match) nozzleDiameter = parseFloat(match[1])
        }
        // Cura: ;NOZZLE:0.4
        if (trimmedLine.startsWith(';NOZZLE:')) {
            nozzleDiameter = parseFloat(trimmedLine.replace(';NOZZLE:', '').trim())
        }

        // === LAYER HEIGHT ===
        // Cura: ;Layer height: 0.2
        if (trimmedLine.includes('Layer height:')) {
            const match = trimmedLine.match(/Layer height:\s*([\d.]+)/)
            if (match) layerHeight = parseFloat(match[1])
        }
        // PrusaSlicer: ; layer_height = 0.2
        if (trimmedLine.includes('layer_height') && trimmedLine.includes('=')) {
            const match = trimmedLine.match(/layer_height\s*=\s*([\d.]+)/)
            if (match) layerHeight = parseFloat(match[1])
        }

        // === TEMPERATURES ===
        // Parse M104 (set nozzle temp) and M140 (set bed temp)
        if (!trimmedLine.startsWith(';')) {
            // M104 S200 - set nozzle temp
            if (trimmedLine.startsWith('M104') || trimmedLine.startsWith('M109')) {
                const match = trimmedLine.match(/S(\d+)/)
                if (match && !nozzleTemp) nozzleTemp = parseInt(match[1])
            }
            // M140 S60 - set bed temp
            if (trimmedLine.startsWith('M140') || trimmedLine.startsWith('M190')) {
                const match = trimmedLine.match(/S(\d+)/)
                if (match && !bedTemp) bedTemp = parseInt(match[1])
            }
        }

        // === PRINT TIME ===
        // Cura format: ;TIME:1234 (in seconds)
        if (trimmedLine.startsWith(';TIME:')) {
            const seconds = parseInt(trimmedLine.replace(';TIME:', '').trim())
            if (!isNaN(seconds)) {
                printTimeMinutes = Math.ceil(seconds / 60)
            }
        }
        // PrusaSlicer format: ; estimated printing time (normal mode) = 1h 23m 45s
        if (trimmedLine.includes('estimated printing time')) {
            const match = trimmedLine.match(/(\d+)h\s*(\d+)m\s*(\d+)s/)
            if (match) {
                const hours = parseInt(match[1]) || 0
                const minutes = parseInt(match[2]) || 0
                const seconds = parseInt(match[3]) || 0
                printTimeMinutes = hours * 60 + minutes + Math.ceil(seconds / 60)
            } else {
                // Try format: 1d 2h 3m 4s
                const dayMatch = trimmedLine.match(/(\d+)d/)
                const hourMatch = trimmedLine.match(/(\d+)h/)
                const minMatch = trimmedLine.match(/(\d+)m/)
                const days = dayMatch ? parseInt(dayMatch[1]) : 0
                const hours = hourMatch ? parseInt(hourMatch[1]) : 0
                const minutes = minMatch ? parseInt(minMatch[1]) : 0
                printTimeMinutes = days * 24 * 60 + hours * 60 + minutes
            }
        }

        // === FILAMENT USAGE ===
        // Cura format: ;Filament used: 0.73581m
        if (trimmedLine.includes(';Filament used:')) {
            const match = trimmedLine.match(/;Filament used:\s*([\d.]+)m/)
            if (match) {
                filamentMm = parseFloat(match[1]) * 1000 // Convert m to mm
            }
        }
        // PrusaSlicer format: ; filament used [mm] = 1234.56
        if (trimmedLine.includes('filament used [mm]')) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match) {
                filamentMm = parseFloat(match[1])
            }
        }
        // PrusaSlicer format: ; filament used [g] = 45.67
        if (trimmedLine.includes('filament used [g]')) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match) {
                filamentGrams = parseFloat(match[1])
            }
        }
        // PrusaSlicer format: ; filament used [cm3] = 12.34
        if (trimmedLine.includes('filament used [cm3]') && filamentGrams === 0) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match) {
                const volumeCm3 = parseFloat(match[1])
                const density = MATERIAL_DENSITY[material] || 1.24
                filamentGrams = volumeCm3 * density
            }
        }
        // Alternative PrusaSlicer format: ; filament_used_mm = 1234.56
        if (trimmedLine.includes('filament_used_mm') || trimmedLine.includes('filament used = ')) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match && filamentMm === 0) {
                filamentMm = parseFloat(match[1])
            }
        }
        // PrusaSlicer total filament: ; total filament used [g] = 45.67
        if (trimmedLine.includes('total filament used')) {
            const matchG = trimmedLine.match(/\[g\]\s*=\s*([\d.]+)/)
            const matchMm = trimmedLine.match(/\[mm\]\s*=\s*([\d.]+)/)
            if (matchG) filamentGrams = parseFloat(matchG[1])
            if (matchMm && filamentMm === 0) filamentMm = parseFloat(matchMm[1])
        }
        // PrusaSlicer: ; filament_used_g = 45.67
        if (trimmedLine.includes('filament_used_g')) {
            const match = trimmedLine.match(/=\s*([\d.]+)/)
            if (match) {
                filamentGrams = parseFloat(match[1])
            }
        }

        // === LAYER COUNT ===
        // Cura format: ;LAYER_COUNT:123
        if (trimmedLine.startsWith(';LAYER_COUNT:')) {
            layerCount = parseInt(trimmedLine.replace(';LAYER_COUNT:', '').trim()) || 0
        }
        // PrusaSlicer format: ; total layers count = 123
        if (trimmedLine.includes('total layers count')) {
            const match = trimmedLine.match(/=\s*(\d+)/)
            if (match) {
                layerCount = parseInt(match[1])
            }
        }
    }

    // If filament grams not found, calculate from mm
    if (filamentGrams === 0 && filamentMm > 0) {
        const radius = FILAMENT_DIAMETER / 2
        const volumeMm3 = Math.PI * radius * radius * filamentMm
        const volumeCm3 = volumeMm3 / 1000
        const density = MATERIAL_DENSITY[material] || 1.24
        filamentGrams = volumeCm3 * density
    }

    // Generate compatibility warnings
    if (bedSizeX && bedSizeX > 300) {
        warnings.push(`Large bed size detected (${bedSizeX}mm). May not fit smaller printers.`)
    }
    if (nozzleDiameter && nozzleDiameter !== 0.4) {
        warnings.push(`Non-standard nozzle diameter (${nozzleDiameter}mm). Standard is 0.4mm.`)
    }
    if (nozzleTemp && nozzleTemp > 260) {
        warnings.push(`High nozzle temperature (${nozzleTemp}°C). Verify printer can handle this.`)
    }
    if (bedTemp && bedTemp > 100) {
        warnings.push(`High bed temperature (${bedTemp}°C). Verify printer can handle this.`)
    }

    return {
        printTimeMinutes,
        filamentMm,
        filamentGrams: Math.round(filamentGrams * 100) / 100,
        layerCount,
        flavor,
        slicer,
        material: detectedMaterial,
        compatibility: {
            bedSizeX,
            bedSizeY,
            bedSizeZ,
            nozzleDiameter,
            layerHeight,
            bedTemp,
            nozzleTemp,
            warnings,
        }
    }
}

/**
 * Check if a file is a G-code file by extension
 */
export function isGcodeFile(file: File): boolean {
    return file.name.toLowerCase().endsWith('.gcode')
}

/**
 * Format print time in human-readable format
 */
export function formatPrintTime(minutes: number): string {
    if (minutes < 60) {
        return `${minutes}m`
    }
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    if (hours < 24) {
        return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`
    }
    const days = Math.floor(hours / 24)
    const remainingHours = hours % 24
    return `${days}d ${remainingHours}h`
}
